import type { Metadata } from "next";
import { Inter as FontSans } from "next/font/google";
import "../globals.css";

export const fontSans = FontSans({
  subsets: ["latin"],
  variable: "--font-sans",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function Layout({ children }: { children: React.ReactNode }) {
  return <div id="layout-app">{children}</div>;
}
