import classNames from "classnames";
import type { Metadata } from "next";
import { Inter as FontSans } from "next/font/google";
import Image from "next/image";
import "../globals.css";
import { SidebarNav } from "./components/Layout/SidebarNav";

export const fontSans = FontSans({
  subsets: ["latin"],
  variable: "--font-sans",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const sidebarNavItems = [
  {
    title: "Productos",
    href: "/dashboard/productos",
  },
  {
    title: "Categorías",
    href: "/dashboard/categorias",
  },
  {
    title: "Restaurante",
    href: "/dashboard/restaurante",
  },
  {
    title: "Pedidos",
    href: "/dashboard/pedidos",
  },
  {
    title: "Carta",
    href: "/dashboard/carta",
  },
];

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body
        className={classNames(
          "min-h-screen bg-background font-sans antialiased",
          fontSans.variable
        )}
      >
        <>
          <div className="md:hidden">
            <Image
              src="/examples/forms-light.png"
              width={1280}
              height={791}
              alt="Forms"
              className="block dark:hidden"
            />
            <Image
              src="/examples/forms-dark.png"
              width={1280}
              height={791}
              alt="Forms"
              className="hidden dark:block"
            />
          </div>
          <div className="hidden space-y-6 p-10 pb-16 md:block">
            <div className="flex flex-col space-y-8 lg:flex-row lg:space-x-12 lg:space-y-0">
              <SidebarNav items={sidebarNavItems} />
              <div className="flex-1 w-full lg:border-l p-8 ">{children}</div>
            </div>
          </div>
        </>
      </body>
    </html>
  );
}
